- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew

- name: Install packages with brew
  homebrew:
    name: "{{item}}"
    state: present
  loop:
    - git
    - vim
    - wget
    - python3
    - node
    - visual-studio-code
  ignore_errors: true

- name: Setup .vimrc
  template:
    src: .vimrc.j2
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
    mode: '0644'

- name: Setup Shell RC File
  template:
    src: shellrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'
