- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew

- name: Install packages with brew
  homebrew:
    name: "{{item}}"
    state: present
  loop:
    - git
    - vim
    - wget
    - python3
    - node
    - visual-studio-code

- name: Setup .vimrc
  template:
    src: .vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
