- name: Install Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew

- name: Install packages with brew
  homebrew:
    name: "{{item}}"
    state: present
  loop:
    - git
    - vim
    - wget
    - python3
    - node
    - visual-studio-code

- name: Clone my_scripts repo
  git:
    repo: "{{my_scripts_repo}}/my_scripts"
    dest: "{{ ansible_env.HOME }}/my_scripts"
    
- name: Symlink python scripts to /usr/local/bin
  file: 
    src: "{{ ansible_env.HOME }}/my_scripts/python_scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: yes
    mode: '0755'
  with_fileglob:
    - "{{ ansible_env.HOME }}/my_scripts/python_scripts/*"

- name: Setup .vimrc
  template:
    src: .vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Setup Shell RC File
  template:
    src: shellrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"

