- name: Detect OS Type
  set_fact:
    target_os: "{{ 'mac' if ansible_facts['os_family'] == 'Darwin' else 'wsl' if 'Microsoft' in ansible_facts['kernel'] else 'linux' }}"
- debug:
    var: target_os
- name: Include OS-Specific Tasks
  include_tasks: "{{ target_os }}.yml"
